version: '3'
services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    working_dir: /var/www/html
    container_name: assessment_php-fpm
    ports:
      - '${APP_BACKEND_PORT-9000}:9000'
    volumes:
      - ./:/var/www/html
    restart: always
    depends_on:
      - mysql

  nginx:
    build:
      context: ./docker/nginx
    container_name: assessment_nginx
    ports:
      - '${APP_PORT-80}:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - php-fpm
  
  mysql:
    image: mysql
    container_name: assessment_mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '${DB_PORT-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USERNAME: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    restart: always
    network:
      - mynet

networks:
  mynet:
    driver: bridge